version: '1.0.0'

services:
  web:
    build: .
    ports:
      - "8000:6666"
    volumes:
      - ./app:/code/app
      - ./.env:/code/.env
    environment:
      - ENVIRONMENT=development
      - QBRAID_API_KEY=${QBRAID_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 6666 --reload